{james wip}
WSU-4110/LAN-Party-App pull request #57
Opened 2020-11-04 20:30 UTC by DambOi

Users can now register for parties. This will need some polish, but that's part of usability. It works. 
Closes #37

2020-11-04 22:06 UTC, ThaddG commented on frontend/src/components/SearchUser/SearchUser.js
> +  console.log('whatever in a string', allUsers);
That console.log isn't needed anymore.

2020-11-04 22:07 UTC, ThaddG commented on frontend/src/components/SearchUser/SearchUser.js
>    const [homeRender, setHomeRender] = useContext(HomeRenderContext);
Don't need homeRender here. That's only for Home.js

2020-11-04 22:07 UTC, ThaddG commented on frontend/src/components/SearchUser/SearchUser.js
> +  } , [homeRender])
This doesn't run, can be removed.

2020-11-05 00:15 UTC, ThaddG requested changes

2020-11-05 00:15 UTC, ThaddG commented on frontend/src/components/ViewParty/ViewParty.js
> +  const Link = `${process.env.REACT_APP_URL}/Party/${props.ID}/Update`;
That link has one too many '/'s. replace it with this:
const Link = `${process.env.REACT_APP_URL}Party/${props.ID}/Update`;

2020-11-05 00:15 UTC, ThaddG commented on frontend/src/components/ViewParty/ViewParty.js
> +    Attendees: props.Attendees.push({ID:props.user.ID,Username: props.user.Username})
I tested this out and it returns an integer. So to fix, declare an array above it, push/concat to it then let the value of the key be the declared array.

2020-11-05 22:00 UTC, merged

2020-11-05 23:39 UTC, ga2599 commented
great work